import type { Metadata } from "next";
import { Lato, Nunito } from "next/font/google";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  display: "swap",
  fallback: ["sans-serif", "arial"],
  variable: "--font-lato",
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  display: "swap",
  fallback: ["sans-serif", "arial"],
  variable: "--font-nunito",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${nunito.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
